### ISSUE TITLE
Duplicate keyword on completion

### ISSUE THREAD

**Issue by huynguyen-95** [ibarban/rhetos-lsp#2]
![image](https://user-images.githubusercontent.com/23207078/50628094-1f24d100-0f69-11e9-93aa-700e6020f5e5.png)

When I type "Sql", there are many suggest as same **SqlDependsOn**

**Comment by ibarban** [comment]
The problem is that there are three SqlDependsOn.
```
    [ConceptKeyword("SqlDependsOn")]
    public class SqlDependsOnPropertyInfo : IConceptInfo
    {
        [ConceptKey]
        public IConceptInfo Dependent { get; set; }
        [ConceptKey]
        public PropertyInfo DependsOn { get; set; }
    }

    [ConceptKeyword("SqlDependsOn")]
    public class SqlDependsOnModuleInfo : IConceptInfo
    {
        [ConceptKey]
        public IConceptInfo Dependent { get; set; }
        [ConceptKey]
        public ModuleInfo DependsOn { get; set; }
    }

    [ConceptKeyword("SqlDependsOn")]
    public class SqlDependsOnDataStructureInfo : IConceptInfo
    {
        [ConceptKey]
        public IConceptInfo Dependent { get; set; }
        [ConceptKey]
        public DataStructureInfo DependsOn { get; set; }
    }
```
This was implemented as in C# but the current way is misleading.
The current implementation shows the property but does not specify the type of property.
All the three concepts have the same property name but different types.

What do you think that the correct way should be?

**Comment by ibarban** [comment]
Maybe we can done something as in C#.
This is how C# works in VSCode when you start typing a method name
![screenshot 4](https://user-images.githubusercontent.com/8143422/50678644-fac80380-0fff-11e9-94a7-062f4ec62d2d.png)
And this is how it works when you have typed the method name and have multiple signatures
![screenshot 5](https://user-images.githubusercontent.com/8143422/50678667-16330e80-1000-11e9-8815-e5fe29568474.png)

**Comment by huynguyen-95** [comment]
If there are many types for one keyword (e.x like **SqlDependsOn**), it just suggest only 1 keyword not  
3 like SqlDependsOn but when you finish typing the keyword, it will show overload and description.
![image](https://user-images.githubusercontent.com/23207078/50679285-72645580-1035-11e9-8116-587eedc0a8b4.png)
