### ISSUE TITLE
Show autocomplete until the concept is fully defined

### ISSUE THREAD

**Issue by ibarban** [ibarban/rhetos-lsp#3]
The current implementation shows the concept description only when you type that keyword.
As soon as you hit space the description of the concept disappears.

The desired behaviour should be that the concept description stays until you have finished typing the concept as in C#.

**Comment by huynguyen-95** [comment]
I agree with concept description stays as in C#. Beside that, with the concept keywords have many ways to use (example like **SqlDependsOn**), it should show overload like in C# too.
